### ISSUE TITLE
[SCS-Multiapi-Plugin][OpenAPI] [AsyncAPI] Problem with Strings in Arrays

### ISSUE THREAD

**Issue by AdrianLagarteraSngular** [sngular/scs-multiapi-plugin#169]
When I try to generate some data in the case of a Array of Strings the result doesn't put properly the String keyword, the result its `List<string>` instead of `List<String>`

```        
players:
    type: array
        items:
          type: string
        default: [ ]
```
<img width="575" alt="Captura de pantalla 2023-01-31 a las 11 55 07" src="https://user-images.githubusercontent.com/103184566/215741326-890bb378-65a1-4532-8fd0-bd6cea088e6a.png">
