### ISSUE TITLE
Publishing Kafka Message with <Key,Value> 

### ISSUE THREAD

**Issue by derdrralf** [sngular/scs-multiapi-plugin#205]
Hello, I am using the multiapi-maven-plugin to generate model classes and it's working great so far. However, I've encountered an issue where I need to implement a publisher that uses the generated interface, but also requires a mandatory kafka key.
I'm still unfamiliar with AsynAPI, so I'm uncertain about what the most effective approach and pattern would be in this scenario. Specifically, I'm wondering if there's a way to extend the interface when the AsyncAPI.yaml file indicates a key binding. Any guidance or suggestions on this matter would be greatly appreciated. 

One approach could be to modify the Interface if a key binding is specified:

```
public interface IPublishOrder{
  void publishOrder(>>String messageKey<<, final Order value);
}
```

so it could be implement in an actual publisher class using the interface:

```
@Override
 public void publishOrder(String messageKey,Order value) {
    kafkaTemplate.send(kafkaConfig.TopicName, messageKey, value.toString());
  }
```

If there is a requirement in the AsyncAPI specification. I found an example for key bindings here:

```
channels:
  test:
    publish:
      message:
        bindings:
          kafka:
            key:
              type: string
              enum: ['myKey']
            schemaIdLocation: 'payload'
            schemaIdPayloadEncoding: '4'
            bindingVersion: '0.4.0'
```
from the AsyncAPI specification https://github.com/asyncapi/bindings/blob/master/kafka/README.md#message

I couldn't find any examples or projects that demonstrate how to use the created producer to publish messages to a Kafka topic with keys. If such an example implementation already exists, it would be great if you could add it to the wiki you're working on. This would help others who are looking for the same functionality and make the project more comprehensive.
